# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'Output_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFileDialog, QWidget, QLabel, QPushButton, QLineEdit, QApplication, QMainWindow
import Tertor


class Ui_OutputWindow(QWidget):
    def __init__(self, OutputWindow):
        super().__init__()
        OutputWindow.setObjectName("OutputWindow")
        OutputWindow.resize(900, 500)
        OutputWindow.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(OutputWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(26, 28, 34);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_1)
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_1)
        self.frame_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_3.setStyleSheet("background-color: rgb(42, 44, 54);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textEdit = QtWidgets.QTextEdit(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgb(56, 59, 68);\n"
                                    "color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.horizontalLayout.addWidget(self.frame_3)
        self.horizontalLayout_2.addWidget(self.frame_1)
        OutputWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(OutputWindow)
        QtCore.QMetaObject.connectSlotsByName(OutputWindow)

        self.rid()

    def retranslateUi(self, OutputWindow):
        pass

    def rid(self):
        t = Tertor.data
        h = t.x
        self.textEdit.setText(str(h))
