########################################################################################################################
##
## BY: AFONIN VLADIMIR ALEKSEEVICH
##
## PROJECT: GYROTRON CAVITY GUI
##
## V: 0.2.0
##
########################################################################################################################
# -*- coding: utf-8 -*-
# Created by: PyQt5 UI code generator 5.15.4
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
########################################################################################################################



from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import matplotlib.pyplot as plt
from numpy import sqrt  # квадратный корень
from numpy import abs  # модуль
from numpy import sin  # синус
from numpy import cos  # косинус
from numpy import tan  # тангенс
from numpy import arcsin  # арксинус
from numpy import arccos  # арккосинус
from numpy import arctan  # арктангенс
from numpy import pi  # пи
from numpy import array  # массив
from numpy import log as ln  # натуральный логарифм
from numpy import log2  # логарифм по остнованию 2
from numpy import log10 as lg  # логарифм по остнованию 10
from numpy import exp  # экспонента
import numpy as np
import sys


class Ui_MainWindow(object):
    """Конструктор окна"""

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(550, 340)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 70, 161, 78))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.Integer_numbers = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.Integer_numbers.setContentsMargins(0, 0, 0, 0)
        self.Integer_numbers.setObjectName("Integer_numbers")
        self.n_int = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.n_int.setFont(font)
        self.n_int.setObjectName("n_int")
        self.Integer_numbers.addWidget(self.n_int, 0, 0, 1, 1)
        self.m_int = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.m_int.setFont(font)
        self.m_int.setObjectName("m_int")
        self.Integer_numbers.addWidget(self.m_int, 1, 0, 1, 1)
        self.n_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.n_lineEdit.setFont(font)
        self.n_lineEdit.setObjectName("n_lineEdit")
        self.Integer_numbers.addWidget(self.n_lineEdit, 0, 1, 1, 1)
        self.m_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.m_lineEdit.setFont(font)
        self.m_lineEdit.setObjectName("m_lineEdit")
        self.Integer_numbers.addWidget(self.m_lineEdit, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 511, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Function = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Function.setContentsMargins(0, 0, 0, 0)
        self.Function.setObjectName("Function")
        self.function = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(20)
        self.function.setFont(font)
        self.function.setObjectName("function")
        self.Function.addWidget(self.function)
        self.function_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.function_lineEdit.setFont(font)
        self.function_lineEdit.setObjectName("function_lineEdit")
        self.Function.addWidget(self.function_lineEdit)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(190, 70, 161, 78))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.Numbers_R0L = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.Numbers_R0L.setContentsMargins(0, 0, 0, 0)
        self.Numbers_R0L.setObjectName("Numbers_R0L")
        self.R0_number = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.R0_number.setFont(font)
        self.R0_number.setObjectName("R0_number")
        self.Numbers_R0L.addWidget(self.R0_number, 0, 0, 1, 1)
        self.L_number = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.L_number.setFont(font)
        self.L_number.setObjectName("L_number")
        self.Numbers_R0L.addWidget(self.L_number, 1, 0, 1, 1)
        self.R0_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.R0_lineEdit.setFont(font)
        self.R0_lineEdit.setObjectName("R0_lineEdit")
        self.Numbers_R0L.addWidget(self.R0_lineEdit, 0, 1, 1, 1)
        self.L_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.L_lineEdit.setFont(font)
        self.L_lineEdit.setObjectName("L_lineEdit")
        self.Numbers_R0L.addWidget(self.L_lineEdit, 1, 1, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(360, 70, 171, 78))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.Numbers_SO = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.Numbers_SO.setContentsMargins(0, 0, 0, 0)
        self.Numbers_SO.setObjectName("Numbers_SO")
        self.Sigma_number = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Sigma_number.setFont(font)
        self.Sigma_number.setObjectName("Sigma_number")
        self.Numbers_SO.addWidget(self.Sigma_number, 0, 0, 1, 1)
        self.Omega_number = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Omega_number.setFont(font)
        self.Omega_number.setObjectName("Omega_number")
        self.Numbers_SO.addWidget(self.Omega_number, 1, 0, 1, 1)
        self.Sigma_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Sigma_lineEdit.setFont(font)
        self.Sigma_lineEdit.setObjectName("Sigma_lineEdit")
        self.Numbers_SO.addWidget(self.Sigma_lineEdit, 0, 1, 1, 1)
        self.Omega_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Omega_lineEdit.setFont(font)
        self.Omega_lineEdit.setObjectName("Omega_lineEdit")
        self.Numbers_SO.addWidget(self.Omega_lineEdit, 1, 1, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 150, 511, 110))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.Numbers_Z = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.Numbers_Z.setContentsMargins(0, 0, 0, 0)
        self.Numbers_Z.setObjectName("Numbers_Z")
        self.zleft_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.zleft_lineEdit.setFont(font)
        self.zleft_lineEdit.setObjectName("zleft_lineEdit")
        self.Numbers_Z.addWidget(self.zleft_lineEdit, 0, 1, 1, 1)
        self.z_start = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.z_start.setFont(font)
        self.z_start.setObjectName("z_start")
        self.Numbers_Z.addWidget(self.z_start, 1, 0, 1, 1)
        self.z_left = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.z_left.setFont(font)
        self.z_left.setObjectName("z_left")
        self.Numbers_Z.addWidget(self.z_left, 0, 0, 1, 1)
        self.zstart_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.zstart_lineEdit.setFont(font)
        self.zstart_lineEdit.setObjectName("zstart_lineEdit")
        self.Numbers_Z.addWidget(self.zstart_lineEdit, 1, 1, 1, 1)
        self.z_right = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.z_right.setFont(font)
        self.z_right.setObjectName("z_right")
        self.Numbers_Z.addWidget(self.z_right, 0, 2, 1, 1)
        self.z_finish = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.z_finish.setFont(font)
        self.z_finish.setObjectName("z_finish")
        self.Numbers_Z.addWidget(self.z_finish, 1, 2, 1, 1)
        self.zright_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.zright_lineEdit.setFont(font)
        self.zright_lineEdit.setObjectName("zright_lineEdit")
        self.Numbers_Z.addWidget(self.zright_lineEdit, 0, 3, 1, 1)
        self.zfinish_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.zfinish_lineEdit.setFont(font)
        self.zfinish_lineEdit.setObjectName("zfinish_lineEdit")
        self.Numbers_Z.addWidget(self.zfinish_lineEdit, 1, 3, 1, 1)
        self.dz = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dz.setFont(font)
        self.dz.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.dz.setObjectName("dz")
        self.Numbers_Z.addWidget(self.dz, 2, 2, 1, 1)
        self.dz_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.dz_lineEdit.setFont(font)
        self.dz_lineEdit.setObjectName("dz_lineEdit")
        self.Numbers_Z.addWidget(self.dz_lineEdit, 2, 3, 1, 1)
        self.nMods = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(20)
        self.nMods.setFont(font)
        self.nMods.setObjectName("nMods")
        self.Numbers_Z.addWidget(self.nMods, 2, 0, 1, 1)
        self.nMods_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.nMods_lineEdit.setFont(font)
        self.nMods_lineEdit.setObjectName("nMods_lineEdit")
        self.Numbers_Z.addWidget(self.nMods_lineEdit, 2, 1, 1, 1)
        self.RUN_Button = QtWidgets.QPushButton(self.centralwidget)
        self.RUN_Button.setGeometry(QtCore.QRect(170, 270, 200, 55))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.RUN_Button.setFont(font)
        self.RUN_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RUN_Button.setObjectName("RUN_Button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # вызыв функции run, для начала работы программы
        self.run()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gyrotron Cavity"))
        self.n_int.setText(_translate("MainWindow", "n"))
        self.m_int.setText(_translate("MainWindow", "m"))
        self.function.setText(_translate("MainWindow", "R(z)"))
        self.R0_number.setText(_translate("MainWindow", "R0"))
        self.L_number.setText(_translate("MainWindow", "L"))
        self.Sigma_number.setText(_translate("MainWindow", "Sigma"))
        self.Omega_number.setText(_translate("MainWindow", "Omega"))
        self.z_start.setText(_translate("MainWindow", "z start"))
        self.z_left.setText(_translate("MainWindow", "z left"))
        self.z_right.setText(_translate("MainWindow", "z right"))
        self.z_finish.setText(_translate("MainWindow", "z finish "))
        self.dz.setText(_translate("MainWindow", "dz"))
        self.nMods.setText(_translate("MainWindow", "nMods"))
        self.RUN_Button.setText(_translate("MainWindow", "Run"))

    # выполнение функции "run" по нажатию кнопки "Run"
    def run(self):
        self.RUN_Button.clicked.connect(self.launch)

    # присваивание значений переменым
    def launch(self):
        try:
            n = int(self.n_lineEdit.text())
            m = int(self.m_lineEdit.text())
            R0 = float(self.R0_lineEdit.text())
            L = float(self.L_lineEdit.text())
            nMods = int(self.nMods_lineEdit.text())
            sigma = float(self.Sigma_lineEdit.text())
            omega = float(self.Omega_lineEdit.text())
            z_left = float(self.zleft_lineEdit.text())
            z_right = float(self.zright_lineEdit.text())
            z_start = float(self.zstart_lineEdit.text())
            z_finish = float(self.zfinish_lineEdit.text())
            dz = float(self.dz_lineEdit.text())
            z = np.arange(z_start, z_finish, 0.001)
            Rz = self.R_function(z, n, m, R0, L, nMods, sigma, omega, z_left, z_right, z_start, z_finish, dz)

            c0 = 299792458
            mu0 = 4 * pi * 10 ** (-7)  # мю 0
            epsilon0 = 8.854187935757958 * 10 ** (-12)
            e0 = 1.602176620898 * 10 ** (-19)
            m0 = 9.10938356 * 10 ** (-31)
            mm = 10 ** (-3)
            ms = 10 ** (-3)
            GHz = 10 ** 9

            #  поcтроение графика
            plt.xlabel('z, мм', fontsize=18, fontweight="bold")
            plt.ylabel('R(z), мм', fontsize=18, fontweight="bold")
            plt.tick_params(axis='both', which='major', labelsize=20)
            plt.grid(True)
            plt.plot(z, Rz, "k")
            plt.plot(z, -Rz, "k")
            plt.show()

        except:
            error = QMessageBox()
            error.setWindowTitle("Ошибка")
            error.setText("Ошибка ввода")
            error.setIcon(QMessageBox.Warning)
            error.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
            error.setDetailedText("Данные введены не корректно или заполнены не все поля ввода")
            error.exec_()


        """        numn = 0  # Функция бессуля
                omega0 = c0 * numn / R0
                f0 = omega0 / (2 * pi)

                # Сетка по координате
                znorm = L
                z1 = z_start
                zN = z_finish
                NN = ((zN - z1) / dz // Round) + 1
                zi = z1 + dz * Range[0, NN - 1]
                zi[[-1]] = zN
                ksii = zi / znorm
                Delksi = dz / znorm

                # Сдвиг
                Omega0 = (numn dz / L) ^ 2 OmegaL2divR20;
                Shift0 = (numn dz / L) ^ 2 OptionValue["Shift"]

                # массивы
                Ri = np.array([0.0] * NN)
                deltai = np.array([0.0] * NN)
                di = np.array([0.0] * NN)

                # массив радиусов
                Ri = R / zi

                # Массив расстроек
                deltai = (numn dz / R0) ^ 2(1 - R0 ^ 2 / Ri ^ 2)"""

    #  Функция R(z)
    def R_function(self, z=0, n=0, m=0, R0=0, L=0, nMods=0, sigma=0, omega=0, z_left=0, z_right=0, z_start=0,
                   z_finish=0, dz=0):
        return eval(self.function_lineEdit.text())


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
